# Generated by Django 3.1.4 on 2021-02-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.PositiveIntegerField(max_length=30),
        ),
    ]
