# Generated by Django 3.1.4 on 2021-02-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210216_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.PositiveIntegerField(),
        ),
    ]
